apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0
  annotations:
    field.cattle.io/creatorId: "user-m9fwq"
    pv.kubernetes.io/bound-by-controller: "yes"
spec:
  storageClassName: hostpath
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/rancher/pv/pv0"
    type: DirectoryOrCreate