apiVersion: v1
kind: Secret
metadata:
  name: rathena-secret
  labels:
    app: rathena
    type: Opaque
data:
  mysql-password: {{ .Values.mysql.root_password | b64enc }}
  intersrv-password: {{ .Values.rathena.intersrv_password | b64enc }}
